### PR TITLE
Do not use hook alias - follow-up, bump version to 2.1.1

### PR DESCRIPTION
**Pull request by SharakPL**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Follow-up of https://github.com/PrestaShop/ps_mainmenu/pull/56 and https://github.com/PrestaShop/PrestaShop/pull/26601
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | -
| How to test?  | No need QA

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Comment by SharakPL** [comment]
@PierreRambaud sorry about that 😳 Just small rearrangement.

**Comment by PierreRambaud** [comment]
PHP CS fixer is still not happy :sweat_smile:

**Comment by SharakPL** [comment]
Should be good now. #34 left some unwanted spaces 😉

**Review by PierreRambaud — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @SharakPL, @Progi1984,

>No need QA

We don't need QA to test this PR?

If not, @SharakPL, can you create a new issue to describe the steps to reproduce the issue?

Thank you!

**Comment by PierreRambaud** [comment]
> Hi @SharakPL, @Progi1984,
> 
> > No need QA
> 
> We don't need QA to test this PR?
> 
> If not, @SharakPL, can you create a new issue to describe the steps to reproduce the issue?
> 
> Thank you!

Yes, QA is not needed here

**Comment by SharakPL** [comment]
I was just following PR specs from https://github.com/PrestaShop/ps_mainmenu/pull/56 (changes are all the same except version numbers).
I didn't even know what QA means at the time. I thought it's something with questions and answers 😂 Never would have guessed it's Quality Assurance!

**Comment by khouloudbelguith** [comment]
> > Hi @SharakPL, @Progi1984,
> > > No need QA
> > 
> > 
> > We don't need QA to test this PR?
> > If not, @SharakPL, can you create a new issue to describe the steps to reproduce the issue?
> > Thank you!
> 
> Yes, QA is not needed here

@PierreRambaud thanks for your feedback.
Can you please remove the Waiting for QA label?

Thanks!

**Comment by PierreRambaud** [comment]
Thank you @SharakPL

**Pull request merged**
